data("AirPassengers")
passengers_ts <- ts(AirPassengers, frequency = 12)
plot(passengers_ts, main = "Time Series Plot")
decomposed <- decompose(passengers_ts)
par(mfrow = c(4, 1))
plot(decomposed)
acf(passengers_ts, main = "ACF")
pacf(passengers_ts, main = "PACF")
